services:
  server:
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
    image: postgres
    restart: always
    expose:
      - 5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    env_file:
      - '.env.development'
    environment:
      - NODE_ENV=development
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  pgdata:
