services:
  server:
    env_file:
      - .env.production
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    env_file:
      - .env.production
    image: postgres
    restart: always
    user: postgres
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
