export const comments = [
  {
    id: 1,
    text: "Different comment text 1",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 2,
      username: "user2",
      email: "user2@example.com",
      siteUrl: null,
    },
    replies: [
      {
        id: 5,
        text: "Different comment text 5",
        createdAt: "2024-02-19T16:48:38.532Z",
        user: {
          id: 1,
          username: "user1",
          email: "user1@example.com",
          siteUrl: null,
        },
        replies: [],
      },
      {
        id: 2,
        text: "Different comment text 2",
        createdAt: "2024-02-19T16:48:38.532Z",
        user: {
          id: 1,
          username: "user1",
          email: "user1@example.com",
          siteUrl: null,
        },
        replies: [
          {
            id: 3,
            text: "Different comment text 3",
            createdAt: "2024-02-19T16:48:38.532Z",
            user: {
              id: 2,
              username: "user2",
              email: "user2@example.com",
              siteUrl: null,
            },
            replies: [
              {
                id: 4,
                text: "Different comment text 4",
                createdAt: "2024-02-19T16:48:38.532Z",
                user: {
                  id: 1,
                  username: "user1",
                  email: "user1@example.com",
                  siteUrl: null,
                },
                replies: [],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 6,
    text: "Different comment text 6",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 7,
    text: "Different comment text 7",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 2,
      username: "user2",
      email: "user2@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 8,
    text: "Different comment text 8",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 2,
      username: "user2",
      email: "user2@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 9,
    text: "Different comment text 9",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 10,
    text: "Different comment text 10",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 11,
    text: "Different comment text 11",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 12,
    text: "Different comment text 12",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [
      {
        id: 35,
        text: "Different comment text 35",
        createdAt: "2024-02-19T16:48:38.532Z",
        user: {
          id: 2,
          username: "user2",
          email: "user2@example.com",
          siteUrl: null,
        },
        replies: [
          {
            id: 44,
            text: "Different comment text 44",
            createdAt: "2024-02-19T16:48:38.532Z",
            user: {
              id: 1,
              username: "user1",
              email: "user1@example.com",
              siteUrl: null,
            },
            replies: [],
          },
        ],
      },
    ],
  },
  {
    id: 13,
    text: "Different comment text 13",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 14,
    text: "Different comment text 14",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 15,
    text: "Different comment text 15",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [
      {
        id: 23,
        text: "Different comment text 23",
        createdAt: "2024-02-19T16:48:38.532Z",
        user: {
          id: 2,
          username: "user2",
          email: "user2@example.com",
          siteUrl: null,
        },
        replies: [],
      },
    ],
  },
  {
    id: 16,
    text: "Different comment text 16",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 17,
    text: "Different comment text 17",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 18,
    text: "Different comment text 18",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 19,
    text: "Different comment text 19",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 20,
    text: "Different comment text 20",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 21,
    text: "Different comment text 21",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 22,
    text: "Different comment text 22",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 24,
    text: "Different comment text 24",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 25,
    text: "Different comment text 25",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 26,
    text: "Different comment text 26",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 2,
      username: "user2",
      email: "user2@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 27,
    text: "Different comment text 27",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 28,
    text: "Different comment text 28",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 29,
    text: "Different comment text 29",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
  {
    id: 30,
    text: "Different comment text 30",
    createdAt: "2024-02-19T16:48:38.532Z",
    user: {
      id: 1,
      username: "user1",
      email: "user1@example.com",
      siteUrl: null,
    },
    replies: [],
  },
];
